# Generated by Django 5.1.15 on 2026-04-05 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='played_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
